var name = prompt("Enter Name :")
var job = prompt("Enter Job :")
var age = prompt("Enter Age :")
alert("The name of the user is "+name)
alert("The user is a "+job)
alert("The user is "+age+" years old.")